Full German Translation
Leopard20/Advanced-Developer-Tools-Localization pull request #4
Opened 2021-01-23 12:03 UTC by Th3Jock3R

Full German Translation

2021-01-23 14:21 UTC, leopard20 commented
Thanks for the German localization.

But I think @R3voA3 claimed it first. Did you read the readme?
https://github.com/leopard20/Advanced-Developer-Tools-Localization/blob/main/README.md

I'll let @R3voA3 decide whether this should be merged

2021-01-23 14:46 UTC, R3voA3 commented on Stringtable.xml
> +				<German>Resette die Modeinstellungen</German>
Einstellungen zurücksetzen

2021-01-23 15:05 UTC, R3voA3 requested changes

2021-01-23 15:05 UTC, R3voA3 commented on Stringtable.xml
> +				<German>Kommentar</German>
Kommentare

2021-01-23 15:05 UTC, R3voA3 commented on Stringtable.xml
> +				<German>Hintergrund der Steuerung</German>
Hintergrund von Steuerungselementen

* Need to check if there is enough space

2021-01-23 15:05 UTC, R3voA3 commented on Stringtable.xml
> +				<German>Rand des Fensters</German>
Fensterrahmen

2021-01-23 15:05 UTC, R3voA3 commented on Stringtable.xml
> +				<German>Es ist nicht empfohlen, dass die Zahl der Punkte schnell variiert</German>
Nicht empfohlen, wenn die Anzahl an Punkten schnell variiert

2021-01-23 15:05 UTC, R3voA3 commented on Stringtable.xml
> +				<German>Höhere Wert bedeutet schnellere Suche, was jedoch auch dazu führen kann, dass es länger eingefrohren ist. 1 = Disabled</German>
Ein größerer Wert sorgt für eine schnellere Suche, kann aber längeres Einfrieren verursachen. 1 = Deaktiviert

2021-01-23 15:05 UTC, R3voA3 commented on Stringtable.xml
> +				<German>Zahl der außerplanmäßigen Suchen</German>
Anzahl von Suchvorgängen (unscheduled)

*unscheduled ist ein Fachbegriff in SQF und sollte nicht übersetzt werden.

2021-01-23 15:05 UTC, R3voA3 commented on Stringtable.xml
> +				<German>Zeigt immer die Debug Konsole</German>
Debug Konsole immer anzeigen

2021-01-23 15:05 UTC, R3voA3 commented on Stringtable.xml
> +				<German>Ersetze die Vanilla Debug Konsole</German>
Standard Debug Konsole ersetzen

2021-01-23 15:05 UTC, R3voA3 commented on Stringtable.xml
> +				<German>Init Komandos beim Starten</German>
Kommandos beim Start initialisieren

2021-01-23 15:05 UTC, R3voA3 commented on Stringtable.xml
> +				<German>Zwischen 1 und 200. Größere Werte können deinen Profile Namespace durcheinanderbringen.</German>
Zwischen 1 und 200. Größere Werte können den Profilenamespace verunreinigen.

2021-01-23 15:05 UTC, R3voA3 commented on Stringtable.xml
> +				<German>Maximale Anzahl der Ausführungs-Historie</German>
Maximale Anzahl des Ausführungsverlaufes

2021-01-23 15:05 UTC, R3voA3 commented on Stringtable.xml
> +				<German>Muss von Leerzeichen, Kommata (,) oder Semikolons (;) separaiert sein</German>
Muss durch Leerzeichen( ), Komma(,) oder Semikolon (;) getrennt sein

2021-01-23 15:05 UTC, R3voA3 commented on Stringtable.xml
> +				<German>Komandos um eine spezielle Farbe zu nutzen</German>
Kommandos welche die Spezialfarbe verwenden

2021-01-23 15:05 UTC, R3voA3 commented on Stringtable.xml
> +				<German>Auswahl</German>
Auswählen

2021-01-23 15:05 UTC, R3voA3 commented on Stringtable.xml
> +				<German>Setzte die formatierung von Kommandos zurück</German>
Setze die Formatierung von Kommandos zurück

2021-01-23 15:05 UTC, R3voA3 commented on Stringtable.xml
> +				<German>Anzahl der Durchläufe</German>
Anzahl an Durchläufen

2021-01-23 15:05 UTC, R3voA3 commented on Stringtable.xml
> +				<German>Ersetze Alla</German>
Alle Ersetzen

2021-01-23 15:05 UTC, R3voA3 commented on Stringtable.xml
> +				<German>Ersetze</German>
Ersetzen

2021-01-23 15:05 UTC, R3voA3 commented on Stringtable.xml
> +				<German>Alle Kopieren</German>
Alle kopieren

2021-01-23 15:05 UTC, R3voA3 commented on Stringtable.xml
> +				<German>Ergebnisse</German>
Ergebnis

2021-01-23 15:05 UTC, R3voA3 commented on Stringtable.xml
> +				<German>Speichern</German>
Anwenden

2021-01-23 15:05 UTC, R3voA3 commented on Stringtable.xml
> +				<German>Übersetzen</German>
Übersetzer

2021-01-23 15:05 UTC, R3voA3 commented on Stringtable.xml
> +				<German>Auswahl</German>
Auswählen

2021-01-23 15:05 UTC, R3voA3 commented on Stringtable.xml
> +				<German>Historie</German>
Verlauf

2021-01-23 15:05 UTC, R3voA3 commented on Stringtable.xml
> +				<German>Ausruck:</German>
Ausdruck:

2021-01-23 15:05 UTC, R3voA3 commented on Stringtable.xml
> +				<German>Suche in Addons/Functionen</German>
In Erweiterungen/Funktionen suchen

2021-01-23 15:05 UTC, R3voA3 commented on Stringtable.xml
> +				<German>Ausführungshistorie</German>
Ausführungsverlauf

2021-01-23 15:05 UTC, R3voA3 commented on Stringtable.xml
> +				<German>Zu Notepad++ exportieren</German>
Nach Notepad++ exportieren

2021-01-23 15:05 UTC, R3voA3 commented on Stringtable.xml
> +				<German>Dienstprogramme</German>
Utilities 

* That's how they are called on the BIKI as well.

2021-01-23 15:05 UTC, R3voA3 commented on Stringtable.xml
> +				<German>Functionen</German>
Funktionen

2021-01-23 15:05 UTC, R3voA3 commented on Stringtable.xml
> +				<German>Suche in den Einstellungen</German>
In Eigenschaften suchen

2021-01-23 15:05 UTC, R3voA3 commented on Stringtable.xml
> +				<German>Lesezeichen zu den aktuellen Konfigurationspfad</German>
Aktuellen Konfigurationspfad als Lesezeichen speichern

2021-01-23 15:05 UTC, R3voA3 commented on Stringtable.xml
> +				<German>Objekte</German>
Objekt

2021-01-23 16:22 UTC, Th3Jock3R commented
> Thanks for the German localization.
> 
> But I think @R3voA3 claimed it first. Did you read the readme?
> https://github.com/leopard20/Advanced-Developer-Tools-Localization/blob/main/README.md
> 
> I'll let @R3voA3 decide whether this should be merged

ohh, i checked it yesterday and there i didnt saw one, so i done the translation :-P Of Cause, @R3voA3 can choose.

He also made some remarks on my commit, i will check them and correct my mistakes

2021-01-24 00:43 UTC, Th3Jock3R commented
added the recommended Changes from @R3voA3

2021-01-24 21:32 UTC, merged

2021-01-25 22:31 UTC, Leopard20 commented
@Th3Jock3R Updated the mod with your localization
Please let me know how it looks

2021-01-25 22:39 UTC, Th3Jock3R commented
/done